# -*- mode: ruby -*-
# vi: set ft=ruby :

### Configuration
BOX = 'generic/ubuntu1604'
OS_TYPE = BOX.split('/')[-1] # i.e. rhel, centos, ubuntu
OS_VERSION = OS_TYPE.gsub(/[^0-9]/, '') # i.e. 6 or 18.04 or 9
BOX_NAME = "workstation.bootstrap"
BOX_RAM_MB = '2048'
BOX_CPU_COUNT = '1'
BOX_IP = '10.11.12.43'
CHEF_WORKSTATION_VERSION = '20.8.111'
HOSTNAME = "workstation.bootstrap"

### Include our localized settings and any overrides
require './settings.rb'

### Apply Configuration
if OS_TYPE =~ /Ubuntu\w+/i
  OS_VERSION = OS_VERSION.insert(2, '.')
end

Vagrant.configure('2') do |config|
  config.vm.hostname = HOSTNAME
  config.vm.box = BOX

  config.vm.network 'private_network', ip: BOX_IP

  ### Map the chef-server directory to the ~/vbox/server directory in the box
  config.vm.synced_folder SERVER_SHARED_DIRECTORY, "/home/vagrant/vbox/server"

  ### Map the chef-node directory to the ~/vbox/node directory in the box
  config.vm.synced_folder NODE_SHARED_DIRECTORY, "/home/vagrant/vbox/node"

  ### Map the chef-workstation directory to the ~/vbox/workstation directory in the box
  config.vm.synced_folder WORKSTATION_SHARED_DIRECTORY, "/home/vagrant/vbox/workstation"

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = BOX_RAM_MB
    vb.cpus = BOX_CPU_COUNT
    vb.name = BOX_NAME
  end

  config.vm.provision 'shell', path: 'provision.sh',
    args: [CHEF_WORKSTATION_VERSION, OS_TYPE, OS_VERSION]
end
