# -*- mode: ruby -*-
# vi: set ft=ruby :

### Configuration
BOX = 'generic/ubuntu1604'
OS_TYPE = BOX.split('/')[-1] # i.e. rhel, centos, ubuntu
OS_VERSION = OS_TYPE.gsub(/[^0-9]/, '') # i.e. 6 or 18.04 or 9
BOX_NAME = "server.bootstrap"
BOX_RAM_MB = '4096'
BOX_CPU_COUNT = '1'
BOX_IP = '10.11.12.13'
CHEF_SERVER_VERSION = '13.2.0'
HOSTNAME = "server.bootstrap"

### Include our localized settings and any overrides
require './settings.rb'

### Apply Configuration
if OS_TYPE =~ /Ubuntu\w+/i
  OS_VERSION = OS_VERSION.insert(2, '.')
end

Vagrant.configure('2') do |config|
  config.vm.hostname = HOSTNAME
  config.vm.box = BOX

  config.vm.network 'private_network', ip: BOX_IP

  ### Open ports to the Chef Automate dashboard
  #config.vm.network "forwarded_port", guest_ip: BOX_IP, guest: 80, host: 80
  #config.vm.network "forwarded_port", guest_ip: BOX_IP, guest: 443, host: 443

  ### Map a local directory to a "shared" directory in the box
  config.vm.synced_folder SHARED_DIRECTORY, "/home/vagrant/vbox"

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = BOX_RAM_MB
    vb.cpus = BOX_CPU_COUNT
    vb.name = BOX_NAME
  end

  config.vm.provision 'shell', path: 'provision.sh',
    args: [CHEF_SERVER_VERSION, OS_TYPE, OS_VERSION]
end
